### ISSUE TITLE
The Email Verification

### ISSUE THREAD

**Issue by asenawritescode** [samuelmaina/online-shop#30]
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Mon Jun 06 09:16:48 UTC 2022
> There was an unexpected error (type=Not Found, status=404).

The above were errors from the Heruko link (https://sm-online-shop.herokuapp.com/)
I was trying to create an acc.

**Comment by samuelmaina** [comment]
Worked on it. The email  verfication is working
